name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: db
          POSTGRES_PASSWORD: db
          POSTGRES_DB: db_test
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: pdo, pgsql, pdo_pgsql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Copy environment file
        run: cp .env.github-actions .env

      - name: Run PHPUnit
        run: composer test
  test:
    uses: poymanov/actions/.github/workflows/test.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0']
  stan:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: db
          POSTGRES_PASSWORD: db
          POSTGRES_DB: db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Uninstall Telescope dependency
        run: composer remove laravel/telescope

      - name: Copy environment file
        run: cp .env.github-actions .env

      - name: Run migrations
        run: php artisan migrate

      - name: Run Laravel IDE Helper
        run: composer ide-helper-models

      - name: Run Larastan
        run: composer phpstan
